### ISSUE TITLE
how to cancel bind 127.0.0.1

### ISSUE THREAD

**Issue by hisenyuan** [AliyunContainerService/redis-cluster#14]

**Comment by ScottAlone** [comment]
1. configure ports you what to expose
```
master:
  image: redis:3
  ports:
    - "7001:6379"
slave:
  image: redis:3
  command: redis-server --slaveof redis-master 6379
  links:
    - master:redis-master
  ports:
    - "7002:6379"
sentinel:
  build: sentinel
  environment:
    - SENTINEL_DOWN_AFTER=5000
    - SENTINEL_FAILOVER=5000
  links:
    - master:redis-master
    - slave
  ports:
    - "7003:26379"
```
2. modify the Dockerfile
because we have only one redis sentinel, change the value below from 2 to 1
```
ENV SENTINEL_QUORUM 1
```
3. docker-compose build
4. check your firewall/iptables, be sure you have exposed the port 7001-7003 configured above

ps. if you what to scale the number of salves or sentinels, add more instance in the docker-compose.yml

**Comment by ScottAlone** [comment]
1. configure ports you what to expose
```
master:
  image: redis:3
  ports:
    - "7001:6379"
slave:
  image: redis:3
  command: redis-server --slaveof redis-master 6379
  links:
    - master:redis-master
  ports:
    - "7002:6379"
sentinel:
  build: sentinel
  environment:
    - SENTINEL_DOWN_AFTER=5000
    - SENTINEL_FAILOVER=5000
    - SENTINEL_QUORUM 1
  links:
    - master:redis-master
    - slave
  ports:
    - "7003:26379"
```

what were modified:

* add ports configuration
* add ```SENTINEL_QUORUM 1``` in sentinel



2. check your firewall/iptables, be sure you have exposed the port 7001-7003 configured above




ps: if you what to scale the number of salves or sentinels, add more instance in the docker-compose.yml

reference: https://redis.io/topics/sentinel
