### ISSUE TITLE
howto make "redis-server --slaveof" work for redis node with protected mode 

### ISSUE THREAD

**Issue by crossz** [AliyunContainerService/redis-cluster#4]
If I use 'redis-server --requirepass XXX' or attach my redis.conf with requirepass directive, I could not make the command of 'redis-server --slaveof' work within the slave container.

do you know how to fix this?

**Comment by crossz** [comment]
Figure it out.

```
redis-cli -h slave -a master-password config set masterauth master-password 
redis-cli -h slave -a masterpassword slaveof redis-master 6379
```

**Comment by denverdino** [comment]
nice!

**Comment by crossz** [comment]
but it seems can not do failover correctly after the redis-master recovered.......

**Comment by crossz** [comment]
OK. fix it.

I put the --slaveof into the entrypoint.sh within sentinel.

while the "command" of docker-compose.yml should be like following:

```
master:
  image: redis:3
  command: redis-server --requirepass PW --masterauth PW
slave:
  image: redis:3
  command: redis-server --requirepass PW --masterauth PW
  links:
    - master:redis-master
sentinel:
  build: sentinel
  environment:
    - SENTINEL_DOWN_AFTER=5000
    - SENTINEL_FAILOVER=5000
    - REQUIREPASS=PW
  links:
    - master:redis-master
    - slave
```
